memo/urls.py
from django.urls import path
from . import views
# 正在部署的应用的名称
app_name = 'memo'

urlpatterns = [
    path('list/', views.memo_list, name='list'),
    path('detail/<int:id>/', views.memo_detail, name='detail'),
    path('delete/<int:id>/', views.memo_delete, name='delete'),
    path('create/', views.memo_create, name='create'),
]

time_plan_design/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('year.urls', namespace='main')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('memo/', include('memo.urls', namespace='memo')),
    path('timeplan/', include('timeplan.urls', namespace='timeplan')),
    path('toolbox/', include('toolbox.urls', namespace='toolbox')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

memo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from ckeditor.fields import RichTextField

class Memo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = RichTextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

memo/forms.py
# 引入表单类
from django import forms
# 引入文章模型
from .models import Memo

# 写文章的表单类
class MemoForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = Memo
        # 定义表单包含的字段
        fields = ('title', 'body')

memo/views.py
# 引入redirect重定向模块
from django.shortcuts import render, redirect
# 引入HttpResponse
from django.http import HttpResponse
# 引入刚才定义的ArticlePostForm表单类
from .forms import MemoForm
# 引入User模型
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
# 导入数据模型ArticlePost
from .models import Memo

@login_required(login_url='/userprofile/login/')
def memo_list(request):
    # 取出所有博客文章
    memos = Memo.objects.filter(author=request.user)
    # 需要传递给模板（templates）的对象
    context = { 'memos': memos }
    # render函数：载入模板，并返回context对象
    return render(request, 'memo/list.html', context)

def memo_detail(request, id):
    # 取出相应的文章
    memo = Memo.objects.get(id=id)
    # 需要传递给模板的对象
    context = { 'memo': memo }
    # 载入模板，并返回context对象
    return render(request, 'memo/detail.html', context)

# 删文章
def memo_delete(request, id):
    # 根据 id 获取需要删除的文章
    memo = Memo.objects.get(id=id)
    # 调用.delete()方法删除文章
    memo.delete()
    # 完成删除后返回文章列表
    return redirect("memo:list")

@login_required(login_url='/userprofile/login/')
def memo_create(request):
    # 判断用户是否提交数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        memo_post_form = MemoForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if memo_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_memo = memo_post_form.save(commit=False)
            # 指定数据库中 id=1 的用户为作者
            # 如果你进行过删除数据表的操作，可能会找不到id=1的用户
            # 此时请重新创建用户，并传入此用户的id
            new_memo.author = User.objects.get(id=request.user.id)
            # 将新文章保存到数据库中
            new_memo.save()
            # 完成后返回到文章列表
            return redirect("memo:list")
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    else:
        # 创建表单类实例
        memo_post_form = MemoForm()
        # 赋值上下文
        context = { 'memo_post_form': memo_post_form }
        # 返回模板
        return render(request, 'memo/create.html', context)

templates/memo/create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    编写备忘录
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">便签标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">便签正文</label>
                    <!-- 文本区域 -->
                    <div>
                        {{ memo_post_form.media }}
                        {{ memo_post_form.body }}
                    </div>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/memo/detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    备忘录详情
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <!-- 标题及作者 -->
        <h1 class="col-12 mt-4 mb-4">{{ memo.title }}</h1>
        <div class="col-12 alert alert-success">
            <a href="#" onclick="confirm_delete()">删除便签</a>
        </div>
        <!-- 正文 -->
        <div class="col-12">
            <p>{{ memo.body | safe }}</p>
        </div>
    </div>
</div>

<script>
    // 删除文章的函数
    function confirm_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "确认删除",
            // 正文
            content: "确认删除便签吗？",
            // 点击确定按钮后调用的回调函数
            yes: function(index, layero) {
                // 指定应当前往的 url
                location.href='{% url "memo:delete" memo.id %}'
            },
        })
    }
</script>
{% endblock content %}

templates/memo/list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    备忘录
{% endblock title %}

{% block content %}
<br>
    <div class="container">
        <div class="row">
            <div class="col-10">
                {% for memo in memos %}
                <!-- 文章内容 -->
                <div class="col-4 mb-4">
                    <!-- 卡片容器 -->
                    <div class="card h-100">
                        <!-- 标题 -->
                        <h4 class="card-header">{{ memo.title }}</h4>
                        <!-- 摘要 -->
                        <div class="card-body">
                            <p class="card-text">{{ memo.body|slice:'30' | safe }}...</p>
                        </div>
                        <!-- 注脚 -->
                        <div class="card-footer">
                            <a href="{% url 'memo:detail' memo.id %}" class="btn btn-primary">查看便签</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="col">
                <a type="button" class="btn btn-info" href="{% url 'memo:create' %}">新建便签</a>
            </div>
        </div>
    </div>
{% endblock content %}