memo/urls.py
from django.urls import path
from . import views
# 正在部署的应用的名称
app_name = 'memo'

urlpatterns = [
    path('list/', views.memo_list, name='list'),
    path('detail/<int:id>/', views.memo_detail, name='detail'),
    path('delete/<int:id>/', views.memo_delete, name='delete'),
    path('create/', views.memo_create, name='create'),
]

time_plan_design/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('year.urls', namespace='main')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('memo/', include('memo.urls', namespace='memo')),
    path('timeplan/', include('timeplan.urls', namespace='timeplan')),
    path('toolbox/', include('toolbox.urls', namespace='toolbox')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

timeplan/urls.py
from django.urls import path
from . import views
# 正在部署的应用的名称
app_name = 'timeplan'

urlpatterns = [
    path('work/', views.workshop, name='workshop'),
    path('work-detail/<int:id>/', views.work_detail, name='detail'),
    path('create/', views.work_create, name='create'),
    path('finish/<int:id>/', views.work_finish, name='finish'),
    path('report/<int:id>/', views.work_report, name='report'),
    path('template-create/', views.t_create, name='tcreate'),
    path('template-work-create/<int:id>/', views.t_work_create, name='twc'),
    path('template-delete/<int:id>/', views.t_delete, name='tdelete'),
]

userprofile/urls.py
from django.urls import path
from . import views
# 正在部署的应用的名称
app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

year/urls.py
from django.urls import path
from . import views
# 正在部署的应用的名称
app_name = 'year'

urlpatterns = [
    path('', views.index, name='index'),
]

templates/back_to_top_func.html
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background:gray;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background:skyblue;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
<!-- 载入静态文件 -->
{% load staticfiles %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    <link rel="bookmark" type="image/x-icon" href="/static/logo.ico"/>
    <link rel="shortcut icon" href="/static/logo.ico">
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
    <!--图标-->
    <link rel="stylesheet" href="https://ico.z01.com/zico.min.css" rel="stylesheet">
    <!--日历时间插件-->
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/js-year-calendar@latest/dist/js-year-calendar.min.css" />
    <!--时钟插件-->
    <link href="{% static 'css/codehim-clock.css' %}" rel="stylesheet"> 
</head>
<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    <div id="wrapper">
        {% block content %}{% endblock content %}
        <div id="push"></div>
    </div>
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/moment.js/2.26.0/moment.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

    <!-- 引入layer.js -->
    <script src="https://cdn.bootcdn.net/ajax/libs/layer/3.1.1/layer.js"></script>
    <!--日历时间插件-->
    <script src="https://unpkg.com/js-year-calendar@latest/dist/js-year-calendar.min.js"></script>
    <!--时钟插件-->  
    <script type="text/javascript" src="{% static 'js/jquery.codehim.clock.js' %}"></script> 
    <script>
        $('#start').datetimepicker();
    </script>
    <script>
        $(document).ready(function(){
            $(".clock-place").CodehimClock({
                clockSize: "original", 
                showSeconds: true, //false to hide seconds hand
                showDate: true, //false to hide date and day
            });
        });
    </script>

    {% include 'back_to_top_func.html' %}
    {% block script %}{% endblock script %}
    <style>
        html, body {
            height: 100%;
            margin: 0;
        }

        #wrapper {
            min-height: 100%;
            margin-bottom: -60px;
        }

        #footer,
        #push {
            height: 60px;
        }
    </style>
</body>

templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <p class="m-0 text-center text-white">CopyRight &copy; 工效提高网站</p>
            <p class="m-0 text-center text-white">Powered by
                <a href="https://www.djangoproject.com/" target="_blank">
                    Django2.1.8
                </a> &
                <a target="_blank" href="https://getbootstrap.com/">
                    Bootstrap4
                </a>
            </p>
    </div>
</footer>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'main:index' %}">工效提高网站</a>
    <div class="collapse navbar-collapse" id="navbarToggler">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'timeplan:workshop' %}">工作台</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'memo:list' %}">备忘录</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:index' %}">万年历</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'toolbox:list' %}">工具箱</a>
            </li>

            {% if user.is_authenticated %}
            <!-- 如果用户已经登录，则显示用户名下拉框 -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'userprofile:logout' %}">退出登录</a>
                    <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                </div>
            </li>
            <!-- 如果用户未登录，则显示 “登录” -->
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
            </li> 
            <li class="nav-item">
                <a class="nav-link" href="{% url 'userprofile:register' %}">注册</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>


{% if user.is_authenticated %}
<form 
    style="display:none;" 
    id="user_delete"
    action="{% url 'userprofile:delete' user.id %}" 
    method="POST"
>
{% csrf_token %}
    <button type="submit">发送</button>
</form>
    <script>
        function user_delete() {
            // 调用layer弹窗组件
            layer.open({
                title: "确认删除",
                content: "确认删除用户资料吗？",
                yes: function(index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endif %}