memo/urls.py
from django.urls import path
from . import views
# 正在部署的应用的名称
app_name = 'memo'

urlpatterns = [
    path('list/', views.memo_list, name='list'),
    path('detail/<int:id>/', views.memo_detail, name='detail'),
    path('delete/<int:id>/', views.memo_delete, name='delete'),
    path('create/', views.memo_create, name='create'),
]

time_plan_design/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('year.urls', namespace='main')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('memo/', include('memo.urls', namespace='memo')),
    path('timeplan/', include('timeplan.urls', namespace='timeplan')),
    path('toolbox/', include('toolbox.urls', namespace='toolbox')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

timeplan/urls.py
from django.urls import path
from . import views
# 正在部署的应用的名称
app_name = 'timeplan'

urlpatterns = [
    path('work/', views.workshop, name='workshop'),
    path('work-detail/<int:id>/', views.work_detail, name='detail'),
    path('create/', views.work_create, name='create'),
    path('finish/<int:id>/', views.work_finish, name='finish'),
    path('report/<int:id>/', views.work_report, name='report'),
    path('template-create/', views.t_create, name='tcreate'),
    path('template-work-create/<int:id>/', views.t_work_create, name='twc'),
    path('template-delete/<int:id>/', views.t_delete, name='tdelete'),
]

timeplan/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Timeplan(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # 用户给出的数据
    title = models.CharField(max_length=100,default="title")
    describe = models.TextField()
    differ = models.IntegerField(default=0)
    num = models.IntegerField(default=1)
    complete = models.BooleanField(default=False)
    start = models.DateTimeField(default=timezone.now,blank=True,null=True)
    finish = models.DateTimeField(default=None,blank=True,null=True)
    # 计算出的数据
    time = models.IntegerField(default=0,blank=True)
    result = models.IntegerField(default=0,blank=True)
    gb4 = models.CharField(max_length=1000,blank=True)
    # 其他数据
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return self.title

class Template(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # 用户给出的数据
    ttitle = models.CharField(max_length=100,default="title")
    tdescribe = models.TextField()
    tdiffer = models.IntegerField(default=0)
    tnum = models.IntegerField(default=1)
    # 其他数据
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.ttitle

timeplan/forms.py
# 引入表单类
from django import forms
# 引入文章模型
from .models import Timeplan,Template

# 写文章的表单类
class TimeplanForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = Timeplan
        # 定义表单包含的字段
        fields = ('title', 'describe', 'differ', 'num', 'start')

# 写文章的表单类
class TemplateForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = Template
        # 定义表单包含的字段
        fields = ('ttitle', 'tdescribe', 'tdiffer', 'tnum')

timeplan/views.py
# 引入redirect重定向模块
from django.shortcuts import render, redirect
# 引入HttpResponse
from django.http import HttpResponse
# 引入刚才定义的ArticlePostForm表单类
from .forms import TimeplanForm, TemplateForm
# 引入User模型
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
# 导入数据模型ArticlePost
from .models import Timeplan, Template
import datetime
from django.utils import timezone

@login_required(login_url='/userprofile/login/')
def workshop(request):
    # 取出所有博客文章
    timeplans = Timeplan.objects.filter(author=request.user)
    templates = Template.objects.filter(author=request.user)
    # 需要传递给模板（templates）的对象
    context = { 'timeplans': timeplans, 'templates': templates }
    # render函数：载入模板，并返回context对象
    return render(request, 'timeplan/workshop.html', context)

def work_detail(request, id):
    # 取出相应的文章
    timeplan = Timeplan.objects.get(id=id)
    # 需要传递给模板的对象
    context = { 'timeplan': timeplan }
    # 载入模板，并返回context对象
    return render(request, 'timeplan/detail.html', context)

@login_required(login_url='/userprofile/login/')
def work_create(request):
    # 判断用户是否提交数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        timeplan_form = TimeplanForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if timeplan_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_timeplan = timeplan_form.save(commit=False)
            # 指定数据库中 id=1 的用户为作者
            # 如果你进行过删除数据表的操作，可能会找不到id=1的用户
            # 此时请重新创建用户，并传入此用户的id
            new_timeplan.author = User.objects.get(id=request.user.id)
            # 将新文章保存到数据库中
            new_timeplan.save()
            # 完成后返回到文章列表
            return redirect("timeplan:workshop")
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    else:
        # 创建表单类实例
        timeplan_form = TimeplanForm()
        # 赋值上下文
        context = { 'timeplan_form': timeplan_form }
        # 返回模板
        return render(request, 'timeplan/create.html', context)

@login_required(login_url='/userprofile/login/')
def work_finish(request, id):
    # 取出所有博客文章
    timeplan = Timeplan.objects.get(id=id)
    timeplan.complete = True
    timeplan.finish = timezone.now()
    finish = timezone.now()
    finish = int(finish.strftime("%Y%m%d%H%M"))
    start = Timeplan.objects.get(id=id).start
    start = int(start.strftime("%Y%m%d%H%M"))
    timeplan.time = finish - start
    timeplan.save()
    # render函数：载入模板，并返回context对象
    return redirect("timeplan:workshop")

@login_required(login_url='/userprofile/login/')
def work_report(request, id):
    # 取出所有博客文章
    timeplan = Timeplan.objects.get(id=id)
    time = Timeplan.objects.get(id=id).time
    differ = Timeplan.objects.get(id=id).differ
    num = Timeplan.objects.get(id=id).num
    result = 2 * num * differ / time
    timeplan.result = result
    if result >= 4:
        timeplan.gb4 = "优秀"
    if result >= 2.5 and result < 4:
        timeplan.gb4 = "良好"
    if result >= 0.7 and result < 2.5:
        timeplan.gb4 = "合格"
    if result < 0.7:
        timeplan.gb4 = "不合格"
    timeplan.save()
    # 赋值上下文
    context = { 'timeplan': timeplan }
    # 返回模板
    return render(request, 'timeplan/report.html', context)

@login_required(login_url='/userprofile/login/')
def t_create(request):
    # 判断用户是否提交数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        template_form = TemplateForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if template_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_template = template_form.save(commit=False)
            # 指定数据库中 id=1 的用户为作者
            # 如果你进行过删除数据表的操作，可能会找不到id=1的用户
            # 此时请重新创建用户，并传入此用户的id
            new_template.author = User.objects.get(id=request.user.id)
            # 将新文章保存到数据库中
            new_template.save()
            # 完成后返回到文章列表
            return redirect("timeplan:workshop")
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    else:
        # 创建表单类实例
        template_form = TemplateForm()
        # 赋值上下文
        context = { 'template_form': template_form }
        # 返回模板
        return render(request, 'timeplan/tcreate.html', context)

@login_required(login_url='/userprofile/login/')
def t_work_create(request, id):
    templates = Template.objects.get(id=id)
    obj = Timeplan()
    obj.author = User.objects.get(id=request.user.id)
    obj.title = templates.ttitle
    obj.describe = templates.tdescribe
    obj.differ = templates.tdiffer
    obj.num = templates.tnum
    obj.start = timezone.now()
    obj.save()
    context = { 'template': templates }
    return redirect("timeplan:workshop")

@login_required(login_url='/userprofile/login/')
def t_delete(request, id):
    # 根据 id 获取需要删除的文章
    template = Template.objects.get(id=id)
    # 调用.delete()方法删除文章
    template.delete()
    # 完成删除后返回文章列表
    return redirect("timeplan:workshop")

templates/timeplan/create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 开始项目 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="describe">简介</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="describe" name="describe" rows="10"></textarea>
                </div>
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="start">开始时间</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="start" name="start">
                </div>
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="differ">难度（1-5）</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="differ" name="differ">
                </div>
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="num">数量</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="num" name="num">
                </div>
                <br>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/timeplan/detail.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    工作详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <!-- 标题及作者 -->
        <h1 class="col-12 mt-4 mb-4">{{ timeplan.title }}</h1>
        <!-- 文章正文 -->
        <div class="col-12">
            <p>{{ timeplan.describe }}</p>
        </div>
    </div>
</div>

{% endblock content %}

templates/timeplan/report.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    工作报告
{% endblock title %}

{% block content %}
<br><img src="https://ss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=2361956380,2183507375&fm=26&gp=0.jpg" alt="img" style="width: 1300px;height: 150px;"><br><br>
<h4>项目名称：{{ timeplan.title }}</h4>
<h5>项目简介：{{ timeplan.describe }}</h5><br>
<h4>开始时间：{{ timeplan.start }}</h4>
<h4>结束时间：{{ timeplan.finish }}</h4>
<h4>难度：{{ timeplan.differ }}</h4>
<h4>工作量：{{ timeplan.num }}</h4><br>
<h4>效率得分：{{ timeplan.result }}</h4>
<h4>效率得分等第：{{ timeplan.gb4 }}</h4><br>
<div class="alert alert-primary" role="alert">
    由于无大众认可的专业效率评定标准，所以效率得分和效率得分等第均属自编公式。<br>计算结果仅供参考，可能有部分错误，欢迎私信jackyfeng201314@163.com前来纠错或提供您的建议。<br>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    自编公式：2×工作难度×工作量÷工作时间
</div>
{% endblock content %}

templates/timeplan/tcreate.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 编写项目模板 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="ttitle">标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="ttitle" name="ttitle">
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="tdescribe">简介</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="tdescribe" name="tdescribe" rows="10"></textarea>
                </div>
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="tdiffer">难度（1-5）</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="tdiffer" name="tdiffer">
                </div>
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="tnum">数量</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="tnum" name="tnum">
                </div>
                <br>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/timeplan/workshop.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    工作台
{% endblock title %}

{% block content %}
<br>
<div class="container">
    <div class="row">
        <div class="col">
            {% for timeplan in timeplans %}
            <hr>
            <h2><a href="{% url 'timeplan:detail' timeplan.id %}"style="color: black;" >{{ timeplan.title }}</a></h2>
            <div>
                <p style="color: gray;">
                    {{ timeplan.describe | slice:'30' }}...
                </p>
            </div>
            {% if timeplan.complete == False %}
            <a role="button" class="btn btn-outline-primary btn-sm" href="{% url 'timeplan:finish' timeplan.id %}">完成工作</a>
            <button type="button" class="btn btn-outline-secondary btn-sm" onclick="bg_not_finish()">查看报告</button>
            {% else %}
            <button type="button" class="btn btn-outline-secondary btn-sm" onclick="gz_not_finish()">完成工作</button>
            <a role="button" class="btn btn-outline-warning btn-sm" href="{% url 'timeplan:report' timeplan.id %}">查看报告</a>
            {% endif %}
            <hr>
            {% endfor %}
        </div>
        <div class="col-5">
            <div class="col">
                <a type="button" class="btn btn-info" href="{% url 'timeplan:create' %}">新建项目</a>
                <a type="button" class="btn btn-info" href="{% url 'timeplan:tcreate' %}">新建项目模板</a>
            </div>
            <br><hr>
            {% for template in templates %}
            <h5>{{ template.ttitle }}</h5>
            <a role="button" class="btn btn-outline-success btn-sm" href="{% url 'timeplan:twc' template.id %}"><i class="zi zi_plusSquare" zico="加号方形"></i></a>
            <a role="button" class="btn btn-outline-danger btn-sm" href="{% url 'timeplan:tdelete' template.id %}"><i class="zi zi_trashalt" zico="垃圾箱竖条"></i></a>
            <br>
            {% endfor %}
            <hr><br>
            <div class="clock-place"></div>
        </div>
    </div>
</div>
<script>
    function bg_not_finish() {
        layer.msg('请先完成该工作，才可以查看工作报告');
    }
</script>
<script>
    function gz_not_finish() {
        layer.msg('已完成该工作，请查看工作报告');
    }
</script>
{% endblock content %}